homepage:
  path: '/'
  controller: App\Shared\Infrastructure\Controller\Homepage
  methods: 'GET'

login:
  path: '/login'
  controller: App\Shared\Infrastructure\Controller\User\Login
  methods: ['GET', 'POST']


logout:
  path: /logout
  methods: GET